### ISSUE TITLE
Search for Artist broken?

### ISSUE THREAD

**Issue by ajcowell** [R3AP3/amogus#5]
Appears that search for artist is broken? 

ajcowell@iMac amogus % python3 amogus.py --artist "Orbital"

  __ _ _ __ ___   ___   __ _ _   _ ___
 / _` | '_ ` _ \ / _ \ / _` | | | / __|
( (_| | | | | | | (_) | (_| | |_| \__ \
 \__,_|_| |_| |_|\___/ \__, |\__,_|___/
repository:             __/ |Ver: 0.3.3
github.com/R3AP3/amogus|___/

**Comment by R3AP3** [comment]
sorry for the wait. You have to specify first that you are searching in the first place otherwise the script will look for an url input. 

Specifying -s or --search and then specifying --artist or -a will work

Example `python3 amogus.py --search --artist "Orbital"`
or even shorter `python3 amogus.py -s -a "Orbital"`

**Comment by R3AP3** [comment]
![grafik](https://user-images.githubusercontent.com/89069925/176050913-79a9d651-405b-4177-9672-1196456a6df4.png)

Here it was also stated in the readme. Prolly wasnt explicit enough tho so sorry my mistake.
